### ISSUE TITLE
html struktur problemi

### ISSUE THREAD

**Issue by samirkarimov** [sevincesedlii/PragmatechFoundationProjectt#1]
![Screenshot_7](https://user-images.githubusercontent.com/24611841/102401383-ace61380-3ffc-11eb-90da-a96cdfe6b3d5.jpg)

Numune hisse

![Screenshot_6](https://user-images.githubusercontent.com/24611841/102401413-b7081200-3ffc-11eb-8395-bd06e210d98b.jpg)
senin hissen..

Burda bezi struktur problemleri var.. sen zehmet olmasa sabah kod yazarken sadece bu hisseni numunede oldugu kimi yazmaga calis . Sadece o hissenin kodlarini ayri papkada yarad ve mene melumat ver o hissede senin bezi struktur problemlerini helledek ki sonrasinda suretli helledebilesen

**Comment by sevincesedlii** [comment]
> ![Screenshot_7](https://user-images.githubusercontent.com/24611841/102401383-ace61380-3ffc-11eb-90da-a96cdfe6b3d5.jpg)
> 
> Numune hisse
> 
> ![Screenshot_6](https://user-images.githubusercontent.com/24611841/102401413-b7081200-3ffc-11eb-8395-bd06e210d98b.jpg)
> senin hissen..
> 
> Burda bezi struktur problemleri var.. sen zehmet olmasa sabah kod yazarken sadece bu hisseni numunede oldugu kimi yazmaga calis . Sadece o hissenin kodlarini ayri papkada yarad ve mene melumat ver o hissede senin bezi struktur problemlerini helledek ki sonrasinda suretli helledebilesen

Salam müəllim,təəssüf ki strukturu bu cür qura bilmədim,yazdığım hissəni yerləşdirmişəm,lakin yenə baxacam ümid edirəm alındıra bilərəm.Bir də zəhmət olmasa deyə bilərsiniz mənim templatimdə ən az neçə səhifəni yazmalıyam

**Comment by sevincesedlii** [comment]
Salam müəllim,təəssüf ki strukturu bu cür qura bilmədim,yazdığım hissəni yerləşdirmişəm,lakin yenə baxacam ümid edirəm alındıra bilərəm.Bir də zəhmət olmasa deyə bilərsiniz mənim templatimdə ən az neçə səhifəni yazmalıyam
